import type { Metadata } from "next";
import { Lora } from 'next/font/google'
import localFont from 'next/font/local'
import "./globals.scss";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

// Configure the Poppins font


const lora = Lora({
  subsets: ['latin'],
  weight: ['400','500','600', '700'],
  style: ['normal', 'italic'],
  display: 'swap',// Optional: controls how the font is displayed during loading
  variable: '--font-lora',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${lora.variable} ${geistMono.variable} ${geistSans.className} antialiased`}
      >
        <div className="w-full flex flex-col items-center bg-stone-50">
          <div className="bg-white max-w-7xl min-h-screen border-x border-solid border-gray-200 py-8 px-20 w-full flex flex-col gap-16 items-center text-slate-700">
            <Navigation/>
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
